---

- name: Install epel release repo
  yum:
    name=nginx
    state=present

- name: Install network packages
  yum:
    name: ['telnet', 'wget', 'net-tools', 'bind-utils', 'connect-proxy', 'socat']
    state: present

- name: Install editor packages
  yum:
    name: ['vim', 'tmux']
    state: present

- name: Install file packages
  yum:
    name: ['dos2unix', 'jq', 'zip', 'unzip', 'lsof', 'mlocate']
    state: present

- name: Install pip
  yum:
    name: ['python-pip']
    state: present

- name: Install git packages
  yum:
    name: ['git', 'git-lfs']
    state: present

- name: Define git config
  become: no
  git_config:
    name="{{ item.name }}"
    value="{{ item.value }}"
    scope=global
  with_items:
    - '{{ git_config_global }}'

- name: Set timezone
  timezone:
    name: Europe/Paris
