---

- name: Install epel release repo
  yum:
    name=nginx
    state=present

- name: Install network packages
  yum:
    name: ['telnet', 'wget', 'net-tools', 'bind-utils', 'connect-proxy', 'socat']
    state: present

- name: Install editor packages
  yum:
    name: ['vim', 'tmux']
    state: present

- name: Install file packages
  yum:
    name: ['dos2unix', 'jq', 'zip', 'unzip', 'lsof', 'mlocate']
    state: present

- name: Install pip
  yum:
    name: ['python-pip']
    state: present

- name: Install git packages
  yum:
    name: ['git', 'git-lfs']
    state: present

- name: Define git config
  become: no
  git_config:
    name="{{ item.name }}"
    value="{{ item.value }}"
    scope=global
  with_items:
    - '{{ git_config_global }}'

- name: Add kubectl repository
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: ['https://packages.cloud.google.com/yum/doc/yum-key.gpg', 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg']

- name: Install kubectl
  yum:
    name: kubectl
    state: present

- name: Install awscli
  pip:
    name: awscli
    state: present

- name: Create /root/.aws directory
  file:
    path: /root/.aws
    state: directory

- name: Create /root/.aws/config
  copy:
    dest: "/root/.aws/config"
    content: |
      [profile oat]
      region = {{ aws.oat.region }}
      role_arn = {{ aws.oat.role_arn }}
      source_profile = default
      output = json
      
      [profile pro]
      region = {{ aws.pro.region }}
      role_arn = {{ aws.pro.role_arn }}
      source_profile = default
      output = json

- name: Create /root/.aws/credentials
  copy:
    dest: "/root/.aws/credentials"
    content: |
      [default]
      aws_access_key_id = {{ aws.access_key }}
      aws_secret_access_key = {{ aws.secret_access_key }}

- name: Download helm
  get_url:
    dest: /tmp/helm-v{{ helm_version }}-linux-amd64.tar.gz
    url: https://kubernetes-helm.storage.googleapis.com/helm-v{{ helm_version }}-linux-amd64.tar.gz

- name: Install helm
  shell: |
      cd /tmp
      tar -xzf helm-v{{ helm_version }}-linux-amd64.tar.gz
      mv linux-amd64/helm /usr/local/bin/helm

- name: Set timezone
  timezone:
    name: Europe/Paris
