---

- name: Install epel release repo
  yum:
    name=nginx
    state=present

- name: Install network packages
  yum:
    name: ['telnet', 'wget', 'net-tools', 'bind-utils', 'connect-proxy', 'socat']
    state: present

- name: Install editor packages
  yum:
    name: ['vim', 'tmux']
    state: present

- name: Install file packages
  yum:
    name: ['dos2unix', 'jq', 'zip', 'unzip', 'lsof', 'mlocate']
    state: present

- name: Install pip
  yum:
    name: ['python-pip']
    state: present

- name: Install git packages
  yum:
    name: ['git', 'git-lfs']
    state: present

- name: Define git config
  become: no
  git_config:
    name="{{ item.name }}"
    value="{{ item.value }}"
    scope=global
  with_items:
    - '{{ git_config_global }}'

- name: Add kubectl repository
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: ['https://packages.cloud.google.com/yum/doc/yum-key.gpg', 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg']

- name: Install kubectl
  yum:
    name: kubectl
    state: present

- name: Install awscli
  pip:
    name: awscli
    state: present

- name: Set timezone
  timezone:
    name: Europe/Paris
