---

- name: Create /root/.ssh directory
  file:
    path: /root/.ssh
    state: directory

- name: Add ssh keys
  copy:
    dest: "/root/.ssh/{{ item.key_name }}"
    src: "{{ item.key_name }}"
    mode: 0600
  with_items: "{{ tunnels }}"
  when: tunnels

- name: Create /root/.ssh/config
  template:
    dest: /root/.ssh/config
    src: config.j2

- name: Add host to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    line: "{{ item }}"
  with_items: "{{ hosts_file }}"
  when: hosts_file
