---

- name: Get checksum value aws-iam-authenticator
  set_fact:
    checksum_value: "{{ lookup('url', '{{ download_url }}aws-iam-authenticator.sha256').split() }}"

- name: Download aws-iam-authenticator
  get_url:
    dest: "/usr/local/bin/aws-iam-authenticator"
    url: "{{ download_url }}aws-iam-authenticator"
    checksum: "sha256:{{ checksum_value[0] }}"
    mode: 0755
    force: no

- name: Create /home/vagrant/.aws directory
  become: no
  file:
    path: /home/vagrant/.aws
    state: directory

- name: Create /home/vagrant/.aws/config
  become: no
  copy:
    dest: "/home/vagrant/.aws/config"
    content: |
      [profile dev]
      region = {{ aws.dev.region }}
      role_arn = {{ aws.dev.role_arn }}
      source_profile = default
      output = json
      [profile oat]
      region = {{ aws.oat.region }}
      role_arn = {{ aws.oat.role_arn }}
      source_profile = default
      output = json
      [profile pro]
      region = {{ aws.pro.region }}
      role_arn = {{ aws.pro.role_arn }}
      source_profile = default
      output = json

- name: Create /home/vagrant/.aws/credentials
  become: no
  copy:
    dest: "/home/vagrant/.aws/credentials"
    content: |
      [default]
      aws_access_key_id = {{ aws.access_key }}
      aws_secret_access_key = {{ aws.secret_access_key }}
