# configure proxy settings if enabled
- name: create dropin directory
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: "directory"
    mode: 0750
    owner: root
    group: root
  when: docker_proxy_enabled == true

- name: add systemd dropin for proxy
  template:
    src: "proxy.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/proxy.conf"
    mode: 0640
    owner: root
    group: root
  when: docker_proxy_enabled == true
  notify: reload and restart systemd docker

- meta: flush_handlers

