---

- name: Define git config
  become: no
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
  - '{{ git_config_global }}'

- name: Create kubenv command
  template:
    dest: /usr/local/bin/kubenv
    src: kubenv.j2
    mode: 0755

- name: Set timezone
  timezone:
    name: Europe/Paris
