---

- name: Define git config
  become: no
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
  - '{{ git_config_global }}'

- name: Create kubenv command
  copy:
    dest: "/usr/local/bin/kubenv"
    src: kubenv.sh
    mode: 0755

- name: Replace role dev
  replace:
    path: "/usr/local/bin/kubenv"
    regexp: "%kubenv_dev%"
    replace: "{{ kubenv.dev }}"

- name: Replace role oat
  replace:
    path: "/usr/local/bin/kubenv"
    regexp: "%kubenv_oat%"
    replace: "{{ kubenv.oat }}"

- name: Replace role pro
  replace:
    path: "/usr/local/bin/kubenv"
    regexp: "%kubenv_pro%"
    replace: "{{ kubenv.pro }}"

- name: Set timezone
  timezone:
    name: Europe/Paris
