---

- name: Get current version of helm
  shell: /usr/local/bin/helm version -c | grep '^Client' | cut -d'"' -f2
  register: current_helm_version

- name: Create temp directory
  tempfile:
    state: directory
    suffix: helm
  register: temp_directory
  when: current_helm_version.stdout != helm_version

- name: Get checksum value
  set_fact:
    checksum_value: "{{ lookup('url', '{{ download_url }}.sha256') }}"
  when: current_helm_version.stdout != helm_version

- name: Download helm
  get_url:
    dest: "{{ temp_directory.path }}/helm-{{ helm_version }}-linux-amd64.tar.gz"
    url: "{{ download_url }}"
    checksum: "sha256:{{ checksum_value }}"
  when: current_helm_version.stdout != helm_version

- name: Unarchive helm
  unarchive:
    dest: "{{ temp_directory.path }}"
    src: "{{ temp_directory.path }}/helm-{{ helm_version }}-linux-amd64.tar.gz"
    remote_src: yes
  when: current_helm_version.stdout != helm_version

- name: Install helm
  command: mv {{ temp_directory.path }}/linux-amd64/helm /usr/local/bin/helm
  when: current_helm_version.stdout != helm_version
