---

- name: Set up Vundle
  become: no
  git:
    dest: /home/vagrant/.vim/bundle/Vundle.vim
    repo: https://github.com/VundleVim/Vundle.vim.git

- name: Create ~/.vimrc
  become: no
  template:
    src: .vimrc.j2
    dest: /home/vagrant/.vimrc

- name: Install Plugins
  become: no
  command: vim +PluginInstall +qall
