---

aws_iam_authenticator_version: 1.12.7/2019-03-27

download_url: https://amazon-eks.s3-us-west-2.amazonaws.com/{{ aws_iam_authenticator_version }}/bin/linux/amd64/

aws:
  dev:
    region: dev_region
    role_arn: dev_role_arn
  oat:
    region: oat_region
    role_arn: oat_role_arn
  pro:
    region: pro_region
    role_arn: pro_role_arn
  access_key: aws_access_key
  secret_access_key: aws_secret_access_key
