---

aws_iam_authenticator_version: 1.12.7/2019-03-27

download_url: https://amazon-eks.s3-us-west-2.amazonaws.com/{{ aws_iam_authenticator_version }}/bin/linux/amd64/

aws:
  profiles:
  access_key:
  secret_access_key:
