main_user: vagrant

proxy:
  enabled: true
  host: proxy.priv.atos.fr
  port: 3128

http_proxy: "http://{{ proxy.host }}:{{ proxy.port }}"
https_proxy: '{{ http_proxy }}'
no_proxy: localhost,127.0.0.1,devbox,.priv.atos.fr,.local

git_config_global:
  - { name: "user.name",  value: "name" }
  - { name: "user.email", value: "email" }

docker_users:
  - '{{ main_user }}'

docker_package: "docker-{{ docker_edition }}-18.06.0.ce-3.el7"

aws:
  oat:
    region: oat_region
    role_arn: oat_role_arn
  pro:
    region: pro_region
    role_arn: pro_role_arn
  access_key: aws_access_key
  secret_access_key: aws_secret_access_key
