
main_user: vagrant

proxy:
  enabled: true
  host: proxy.priv.atos.fr
  port: 3128

http_proxy: "http://{{ proxy.host }}:{{ proxy.port }}"
https_proxy: '{{ http_proxy }}'
no_proxy: localhost,127.0.0.1,devbox,.priv.atos.fr,.local

git_config_global:
- { name: "user.name",  value: "name" }
- { name: "user.email", value: "email" }

docker_users:
- '{{ main_user }}'

docker_package: "docker-{{ docker_edition }}-18.06.0.ce-3.el7"

aws:
  dev:
    region: dev_region
    role_arn: dev_role_arn
  oat:
    region: oat_region
    role_arn: oat_role_arn
  pro:
    region: pro_region
    role_arn: pro_role_arn
  access_key: aws_access_key
  secret_access_key: aws_secret_access_key

kubenv:
  dev: kubenv_dev
  oat: kubenv_oat
  pro: kubenv_pro

aws_iam_authenticator_version: 1.12.7/2019-03-27

helm_version: v2.13.1

tunnel:
  hostname: hostname
  user: tunnel_user
  local_forward:
  - line1
  - line2
  - line3
  key_name: key_name.pem
  hosts:
  - line1
  - line2
  - line3

terraform_version: 0.11.13
