---

- name: Disable CentOS repos
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: "{{ item }}"
    option: enabled
    value: 0
  with_items:
     - base
     - updates
     - extras
     - centosplus

- name: Remove epel-release.noarch package
  yum:
    name: epel-release.noarch
    state: removed

- name: Add GPG-KEY
  rpm_key:
    key: "{{ gpg_key }}"

- name: Add WL repo
  yum:
    name: http://mirrors.atosworldline.com/private/centos/awl/7/main/x86_64/repositories-1.0-74.awl7.noarch.rpm

- name: Add CentOs repo
  yum:
    name: repositories-centos

- name: Enable CentOS extras repo
  ini_file:
    dest: /etc/yum.repos.d/centos.repo
    section: centos-extras
    option: enabled
    value: 1

- name: Disable fastestmirror plugin
  ini_file:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    section: main
    option: enabled
    value: 0

- name: Add kubernetes repo
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: ['https://packages.cloud.google.com/yum/doc/yum-key.gpg', 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg']

- name: Install packages
  yum:
    name: "{{ packages }}"
    state: present

- name: Install awscli
  pip:
    name: awscli
    state: present

